DispatchCrude/Controllers/DriverAppController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Profile;
using Newtonsoft.Json;
using DispatchCrude.Core;
using DispatchCrude.Models;
using DispatchCrude.Models.Sync;
using DispatchCrude.Models.Sync.DriverApp;
using AlonsIT;
using Newtonsoft.Json.Linq;

namespace DispatchCrude.Controllers
{
    public class DriverAppController : Controller
    {
        private DispatchCrudeDB db = new DispatchCrudeDB();
        //
        // GET: /Account/Index

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //
        // POST: /DriverApp/Login

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(string userName, string password)
        {
            Outcome outcome = new Outcome();
            if (string.IsNullOrEmpty(userName) || !Membership.ValidateUser(userName, password))
                outcome.Message = "User Authentication failed";
            else
            {
                int driverID = 0;
                if ((outcome = GetDriverID(userName, out driverID)).Success)
                {   // valid outcome occurred, so return the MasterData instance in the LoginResult
                    return JsonResult(new LoginResult(outcome, MasterData.Init(userName, driverID, ref outcome)));
                }
            }
            // an error occurred, so just return the Outcome
            return JsonResult(new LoginResult(outcome));
        }

        private Outcome GetDriverID(string userName, out int driverID)
        {
            Outcome ret = new Outcome();
            driverID = 0; // default value
            if (!Roles.IsUserInRole(userName, "Driver"))
                ret.Message = "User is not assigned the 'Driver' role";
            else if ((driverID = DBHelper.ToInt32(ProfileBase.Create(userName).GetPropertyValue("DriverID"))) <= 0)
                ret.Message = "User is not assigned to a Carrier Driver account";
            else if (!GetDriverMobileAppEnabled(driverID))
                ret.Message = "Your driver account is not configured for Mobile App access";
            else
                ret.Success = true;
            return ret;
        }
        private bool GetDriverMobileAppEnabled(int driverID)
        {
            using (SSDB ssdb = new SSDB())
            {
                return DBHelper.ToBoolean(ssdb.QuerySingleValue("SELECT MobileApp FROM dbo.tblDriver WHERE ID = {0}", driverID));
            }
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(string userName, string oldPassword, string newPassword)
        {
            Outcome outcome = new Outcome();
            if (!Membership.ValidateUser(userName, oldPassword))
                outcome.Message = "Old Password was invalid";
            else if (!Membership.GetUser(userName).ChangePassword(oldPassword, newPassword))
                outcome.Message = "Invalid new password was provided";
            else
            {
                int driverID = 0;
                if ((outcome = GetDriverID(userName, out driverID)).Success)
                    return JsonResult(new LoginResult(outcome, MasterData.ResetPasswordHash(userName, driverID, ref outcome)));
            }
            // an error occurred, so just return the Outcome
            return JsonResult(new LoginResult(outcome));
        }

        [AllowAnonymous]
        public ActionResult Sync()
        {
            return View();
        }

        // support method
        private ActionResult JsonResult(object data)
        {
            return Content(JsonConvert.SerializeObject(data, SyncDataInput.JSonSettings()));
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Sync(string json)
        {
            Outcome outcome = new Outcome();

            DateTime syncStart = DateTime.Now;

            try
            {
                // deserialize the incoming JSON into a SyncDataInput object
                if (json.Length == 0)
                    outcome.Message = "No JSON was received";
                else
                {
                    SyncDataInput incomingSD = null;
                    try
                    {
                        incomingSD = SyncDataInput.GetFromJSON(json);
                    }
                    catch (Exception e)
                    {
                        throw new Exception("JSON Deserialize error occurred", e);
                    }
                    // if the object is valid, then continue processing
                    if (incomingSD == null)
                        outcome.Message = "Invalid JSON was received";
                    else if (string.IsNullOrEmpty(incomingSD.Master.UserName))
                        outcome.Message = "UserName was missing or invalid";
                    else if (incomingSD.Master != null)
                    {
                        MasterData outgoingMD = MasterData.Sync(incomingSD.Master, ref outcome);
                        if (outcome.Success)
                        {
                            try
                            {
                                // if this is an initial (full) sync, we need to ensure that any "VirtualDelete" records are first cleared (not needed)
                                if (incomingSD.Master.LastSyncUTC.HasValue)
                                {   // do the PUSH synchronization

                                    // get the driver local time zone
                                    byte? TimeZoneID = null;
                                    if (string.IsNullOrEmpty(incomingSD.CurrentAppTzDstOffsets) == false)
                                    {
                                        try
                                        {
                                            int TZoffset = -99;
                                            int.TryParse(incomingSD.CurrentAppTzDstOffsets.Substring(0, incomingSD.CurrentAppTzDstOffsets.IndexOf(",")), out TZoffset);
                                            Models.TimeZone DriverTZ = db.TimeZones.Where(t => t.StandardOffsetHours == TZoffset).FirstOrDefault();
                                            if (DriverTZ != null) TimeZoneID = DriverTZ.ID;
                                        }
                                        catch { }
                                    }

                                    // only update the order if the driver matches (it returns TRUE if something actually changed)
                                    SyncOrders_Tickets(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncOrderTransfers(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncOrderSignatures(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncDriverLocations(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncHos(incomingSD, ref outcome, outgoingMD.UserName, TimeZoneID);

                                    SyncHosSignatures(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncExceptions(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncOrderPhotos(incomingSD, ref outcome, outgoingMD.UserName);

                                    SyncQuestionnaires(incomingSD, ref outcome, outgoingMD.UserName, TimeZoneID);

                                    SyncDispatchMessages(incomingSD, ref outcome, outgoingMD.UserName);

                                }
                            }
                            catch (Exception ex)
                            {
                                outcome.Success = false;
                                outcome.Message = ex.Message;
                            }

                            SyncDataOutput output = new SyncDataOutput(incomingSD.Master.LastSyncUTC, outcome, outgoingMD, incomingSD.OrdersPresent);

                            MarkOrdersDriverSynced(output.Orders);

                            // log the incoming JSON if this associated system setting is enabled
                            if (Settings.SettingsID.DA_DEBUG_SYNC.AsBool())
                            {
                                using (SSDB ssdb = new SSDB())
                                {
                                    ssdb.ExecuteSql("INSERT INTO tblDriverSyncLog(DriverID, IncomingJSON, OutgoingJSON, SyncStart, SyncDate) VALUES ({0}, {1},{2}, {3}, {4})"
                                        , incomingSD.Master.DriverID
                                        , DBHelper.QuoteStr(incomingSD.SerializeAsJson(true)) // suppress non-logged fields
                                        , DBHelper.QuoteStr(output.SerializeAsJson(true)) // suppress non-logged fields
                                        , DBHelper.QuoteStr(syncStart.ToString("yyyy/MM/dd HH:mm:ss.fff"))
                                        , DBHelper.QuoteStr(DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss.fff")));
                                }
                            }

                            return Content(output.SerializeAsJson());
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(string.Format("DriverApp.Sync server exception occurred, JSON={0}", json), ex);
            }
            // just return the failure outcome
            return JsonResult(new SyncDataOutput(outcome));
        }

        private string LogSyncError(int driverID, string error)
        {
            error = error.Replace("The transaction ended in the trigger. ", "");

DispatchCrude/Views/DriverApp/ChangePassword.cshtml
<div style="width: 50%;min-width: 350px;margin-left:auto; margin-right:auto;">
@using (Html.BeginForm("ChangePassword", "DriverApp", null, FormMethod.Post, new { @data_ajax = "false" }))
{
    @Html.ValidationSummary()

    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Change Password (test page)</li>
        <li data-role="header">Please enter your user name and old | new passwords.</li>
        <li data-role="fieldcontain">
            @Html.Label("UserName")
            @Html.TextBox("UserName")            
        </li>

        <li data-role="fieldcontain">
            @Html.Label("OldPassword")
            @Html.Password("OldPassword")
        </li>

        <li data-role="fieldcontain">
            @Html.Label("NewPassword")
            @Html.Password("NewPassword")
        </li>

        <li>
            <input type="submit" value="Change Password" />
        </li>
    </ul>
}
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DispatchCrude/Views/DriverApp/Log.cshtml
@model DispatchCrude.Models.Driver
@{
    ViewBag.Title = "Logs";
    ViewBag.SubTitle = "Driver Sync Log";
}

@using AlonsIT;
@using DispatchCrude.Extensions;

<style>
    .jsonContainer {
        max-height:440px;
        max-width: 600px;
		width:100%;
        overflow:auto;
    }
    pre {
        background-color: ghostwhite;
        border: 1px solid silver;
        padding: 10px 20px;
        margin: 20px; 
    }
    .json-key {
        color: brown;
    }
    .json-value {
        color: navy;
    }
    .json-string {
        color: olive;
    }
</style>
<script type="text/javascript">
    if (!library)
        var library = {};
    library.json = {
        replacer: function (match, pIndent, pKey, pVal, pEnd) {
            var key = '<span class=json-key>';
            var val = '<span class=json-value>';
            var str = '<span class=json-string>';
            var r = pIndent || '';
            if (pKey)
                r = r + key + pKey.replace(/[": ]/g, '') + '</span>: ';
            if (pVal)
                r = r + (pVal[0] == '"' ? str : val) + pVal + '</span>';
            return r + (pEnd || '');
        },
        prettyPrint: function (obj) {
            var jsonLine = /^( *)("[\w]+": )?("[^"]*"|[\w.+-]*)?([,[{])?$/mg;
            return JSON.stringify(obj, null, 3)
               .replace(/&/g, '&amp;').replace(/\\"/g, '&quot;')
               .replace(/</g, '&lt;').replace(/>/g, '&gt;')
               .replace(jsonLine, library.json.replacer);
        }
    };
    var _jsonInt;
    function getJSONInt(url) {
        $.ajax({
            type: "GET",
            url: url,
            dataType: "json",
            async: false,
            success: function (data) { _jsonInt = data; },
            error: function () {
                alert("Error occured")
            }
        });
        return _jsonInt;
    };
    $(function () {
        $(".json").each(function () {
            debugger;
            var url = $(this).parent().siblings(".jsonRef").attr("href");
            var json = getJSONInt(url);
            $(this).html(library.json.prettyPrint(json));
        })
    });
</script>


<div>
    <div class="tabbable">
        <ul class="nav nav-tabs" id="tabmenu">
            @NavigationHelper.PrintTabArray(NavigationHelper.TabSet_Logs, "Tab_DriverSyncLog")
        </ul>
        <div class="tab-content">
            <div class="tab-pane in active">

                @using (Html.BeginForm())
                {
                    <div class="row">
                        <div class="col-md-6">
                            @Html.DropDownList("DriverID", null, "-- Select driver --", htmlAttributes: new { @style = "width:100%" })
                        </div>
                        <div class="col-md-2">
                            <select name="count" class="form-control">
                                <option value="1" @(ViewBag.Count == "1" ? "SELECTED" : "")>1</option>
                                <option value="3" @(ViewBag.Count == "3" ? "SELECTED" : "")>3</option>
                                <option value="25" @(ViewBag.Count == "25" ? "SELECTED" : "")>25</option>
                                <option value="100" @(ViewBag.Count == "100" ? "SELECTED" : "")>100</option>
                                <option value="250" @(ViewBag.Count == "250" ? "SELECTED" : "")>250</option>
                                <option value="100 PERCENT" @(ViewBag.Count == "100 PERCENT" ? "SELECTED" : "")>ALL !!!</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <input class="btn btn-blue shiny" type="submit" value="Go">
                        </div>
                    </div>
                }


                @if (Model != null)
                {
                    System.Data.DataTable data = null;
                    <h2>Log History - @Model.FullName (@Model.ID) - Top @ViewBag.Count</h2>
                    using (SSDB db = new SSDB())
                    {
                        data = db.GetPopulatedDataTable(
                            "SELECT TOP " + (ViewBag.Count ?? "50") + " * FROM tblDriverSyncLog WHERE DriverID = " + Model.ID + " " +
                            "ORDER BY syncdate DESC");
                    }
                    <table class="table table-border" border>
                        <tr>
                            <th>ID</th>
                            <th>SyncDate</th>
                            <th>SyncStart</th>
                            <th>Incoming</th>
                            <th>Outgoing</th>
                        </tr>
                        @foreach (System.Data.DataRow row in data.Rows)
                        {
                            <tr>
                                <td>@row["ID"]</td>
                                <td>@row["SyncDate"]</td>
                                <td>@row["SyncStart"]</td>
                                <td>
                                    <div class="jsonContainer">
                                        <a class="jsonRef" href="~/DriverApp/IncomingJson/@row["ID"]" target="_blank">incoming</a>
                                        <pre><code class="json"></code></pre>
                                    </div>
                                </td>
                                <td>
                                    <div class="jsonContainer">
                                        <a class="jsonRef" href="~/DriverApp/OutgoingJson/@row["ID"]" target="_blank">outgoing</a>
                                        <pre><code class="json"></code></pre>
                                    </div>
                                </td>
                            </tr>
                        }
                    </table>
                }
            </div>
        </div>
    </div>
</div>

<script src="~/scripts/beyondadmin/select2/select2.min.js"></script>
<script>
    $("#DriverID").select2();
</script>

DispatchCrude/Views/DriverApp/Login.cshtml
<div style="width: 50%;min-width: 350px;margin-left:auto; margin-right:auto;">
@using (Html.BeginForm("Login", "DriverApp", null, FormMethod.Post, new { @data_ajax = "false" }))
{
    @Html.ValidationSummary()

    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Login (test page)</li>
        <li data-role="header">Please enter your user name and password.</li>
        
        <li data-role="fieldcontain">
            @Html.Label("UserName")
            @Html.TextBox("UserName")            
        </li>

        <li data-role="fieldcontain">
            @Html.Label("Password")
            @Html.Password("Password")
        </li>

        <li>
            <input type="submit" value="Log in" />
        </li>
    </ul>
}
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DispatchCrude/Views/DriverApp/Sync.cshtml
<div style="width: 50%;min-width: 350px;margin-left:auto; margin-right:auto;">
@using (Html.BeginForm("Sync", "DriverApp", null, FormMethod.Post, new { @data_ajax = "false" }))
{
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Sync (test page)</li>
        <li data-role="header">Sync test page</li>
        <li data-role="fieldcontain">
            @Html.Label("JSON")
            @Html.TextArea("JSON", "", 10, 60, new { style = "min-height: 300px" })            
        </li>

        <li>
            <input type="submit" value="Sync" />
        </li>
    </ul>
}
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}